const CURRENT_DATE_ADD_DAY = 'CURRENT_DATE_ADD_DAY'
const CURRENT_DATE_ADD_MONTH = 'CURRENT_DATE_ADD_MONTH'
const CURRENT_DATE_REMOVE_DAY = 'CURRENT_DATE_REMOVE_DAY'
const CURRENT_DATE_REMOVE_MONTH = 'CURRENT_DATE_REMOVE_MONTH'
const LOAD_DEMANDS = 'LOAD_DEMANDS'
const LOAD_STATUS = 'LOAD_STATUS'

export {
  CURRENT_DATE_ADD_DAY,
  CURRENT_DATE_ADD_MONTH,
  CURRENT_DATE_REMOVE_DAY,
  CURRENT_DATE_REMOVE_MONTH,
  LOAD_DEMANDS,
  LOAD_STATUS,
}
